using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable CA1062, CA1861 // Generated by EF Core.

namespace Audit.Infrastructure.Persistence.Migrations.AuditMigrations;

/// <inheritdoc />
public partial class InitialReadModel : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "audit_events",
            columns: table => new
            {
                EventId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                Source = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                SourceEventId = table.Column<long>(type: "bigint", nullable: false),
                SourceSequence = table.Column<long>(type: "bigint", nullable: false),
                OrganizationId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                OccurredAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                IngestedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                ActorId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                ActorEmail = table.Column<string>(type: "nvarchar(320)", maxLength: 320, nullable: true),
                CorrelationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                ChangeTypeCode = table.Column<int>(type: "int", nullable: false),
                EntityTypeCode = table.Column<int>(type: "int", nullable: false),
                EntityId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                ParentId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                PrimaryKey = table.Column<string>(type: "nvarchar(max)", nullable: true),
                BeforeJson = table.Column<string>(type: "nvarchar(max)", nullable: true),
                AfterJson = table.Column<string>(type: "nvarchar(max)", nullable: true),
                ChangedFieldsJson = table.Column<string>(type: "nvarchar(max)", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_audit_events", x => x.EventId);
            });

        migrationBuilder.CreateTable(
            name: "contract_search",
            columns: table => new
            {
                OrganizationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                ContractId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                Number = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                InternalNumber = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                Subject = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                ContractorName = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                LastSourceSequence = table.Column<long>(type: "bigint", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_contract_search", x => new { x.OrganizationId, x.ContractId });
            });

        migrationBuilder.CreateTable(
            name: "contract_search_aliases",
            columns: table => new
            {
                Id = table.Column<long>(type: "bigint", nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                OrganizationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                ContractId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                Field = table.Column<string>(type: "nvarchar(80)", maxLength: 80, nullable: false),
                Value = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: false),
                IsCurrent = table.Column<bool>(type: "bit", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_contract_search_aliases", x => x.Id);
            });

        migrationBuilder.CreateTable(
            name: "contract_timeline_items",
            columns: table => new
            {
                EventId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                OrganizationId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                ContractId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                RelationshipResolved = table.Column<bool>(type: "bit", nullable: false),
                SourceSequence = table.Column<long>(type: "bigint", nullable: false),
                OccurredAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                CorrelationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                ChangeTypeCode = table.Column<int>(type: "int", nullable: false),
                ChangeKind = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: false),
                EntityTypeCode = table.Column<int>(type: "int", nullable: false),
                EntityKind = table.Column<string>(type: "nvarchar(80)", maxLength: 80, nullable: false),
                Actor = table.Column<string>(type: "nvarchar(320)", maxLength: 320, nullable: false),
                ChangesJson = table.Column<string>(type: "nvarchar(max)", nullable: false),
                DataQualityIssuesJson = table.Column<string>(type: "nvarchar(max)", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_contract_timeline_items", x => x.EventId);
            });

        migrationBuilder.CreateTable(
            name: "import_checkpoints",
            columns: table => new
            {
                Source = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                LastSourceEventId = table.Column<long>(type: "bigint", nullable: false),
                UpdatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_import_checkpoints", x => x.Source);
            });

        migrationBuilder.CreateTable(
            name: "InboxStates",
            columns: table => new
            {
                Id = table.Column<long>(type: "bigint", nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                MessageId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                ConsumerId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                LockId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: true),
                Received = table.Column<DateTime>(type: "datetime2", nullable: false),
                ReceiveCount = table.Column<int>(type: "int", nullable: false),
                ExpirationTime = table.Column<DateTime>(type: "datetime2", nullable: true),
                Consumed = table.Column<DateTime>(type: "datetime2", nullable: true),
                Delivered = table.Column<DateTime>(type: "datetime2", nullable: true),
                LastSequenceNumber = table.Column<long>(type: "bigint", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_InboxStates", x => x.Id);
                table.UniqueConstraint("AK_InboxStates_MessageId_ConsumerId", x => new { x.MessageId, x.ConsumerId });
            });

        migrationBuilder.CreateTable(
            name: "OutboxStates",
            columns: table => new
            {
                OutboxId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                LockId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: true),
                Created = table.Column<DateTime>(type: "datetime2", nullable: false),
                Delivered = table.Column<DateTime>(type: "datetime2", nullable: true),
                LastSequenceNumber = table.Column<long>(type: "bigint", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_OutboxStates", x => x.OutboxId);
            });

        migrationBuilder.CreateTable(
            name: "OutboxMessages",
            columns: table => new
            {
                SequenceNumber = table.Column<long>(type: "bigint", nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                EnqueueTime = table.Column<DateTime>(type: "datetime2", nullable: true),
                SentTime = table.Column<DateTime>(type: "datetime2", nullable: false),
                Headers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                Properties = table.Column<string>(type: "nvarchar(max)", nullable: true),
                InboxMessageId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                InboxConsumerId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                OutboxId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                MessageId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                ContentType = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                MessageType = table.Column<string>(type: "nvarchar(max)", nullable: false),
                Body = table.Column<string>(type: "nvarchar(max)", nullable: false),
                ConversationId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                CorrelationId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                InitiatorId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                RequestId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                SourceAddress = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                DestinationAddress = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                ResponseAddress = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                FaultAddress = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                ExpirationTime = table.Column<DateTime>(type: "datetime2", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_OutboxMessages", x => x.SequenceNumber);
                table.ForeignKey(
                    name: "FK_OutboxMessages_InboxStates_InboxMessageId_InboxConsumerId",
                    columns: x => new { x.InboxMessageId, x.InboxConsumerId },
                    principalTable: "InboxStates",
                    principalColumns: new[] { "MessageId", "ConsumerId" });
                table.ForeignKey(
                    name: "FK_OutboxMessages_OutboxStates_OutboxId",
                    column: x => x.OutboxId,
                    principalTable: "OutboxStates",
                    principalColumn: "OutboxId");
            });

        migrationBuilder.CreateIndex(
            name: "IX_audit_events_OrganizationId_SourceSequence",
            table: "audit_events",
            columns: new[] { "OrganizationId", "SourceSequence" });

        migrationBuilder.CreateIndex(
            name: "IX_audit_events_Source_SourceEventId",
            table: "audit_events",
            columns: new[] { "Source", "SourceEventId" },
            unique: true);

        migrationBuilder.CreateIndex(
            name: "IX_contract_search_InternalNumber",
            table: "contract_search",
            column: "InternalNumber");

        migrationBuilder.CreateIndex(
            name: "IX_contract_search_Number",
            table: "contract_search",
            column: "Number");

        migrationBuilder.CreateIndex(
            name: "IX_contract_search_aliases_OrganizationId_ContractId_Field_Value",
            table: "contract_search_aliases",
            columns: new[] { "OrganizationId", "ContractId", "Field", "Value" },
            unique: true);

        migrationBuilder.CreateIndex(
            name: "IX_contract_search_aliases_OrganizationId_Value",
            table: "contract_search_aliases",
            columns: new[] { "OrganizationId", "Value" });

        migrationBuilder.CreateIndex(
            name: "IX_contract_timeline_items_OrganizationId_ContractId_SourceSequence",
            table: "contract_timeline_items",
            columns: new[] { "OrganizationId", "ContractId", "SourceSequence" });

        migrationBuilder.CreateIndex(
            name: "IX_InboxStates_Delivered",
            table: "InboxStates",
            column: "Delivered");

        migrationBuilder.CreateIndex(
            name: "IX_OutboxMessages_EnqueueTime",
            table: "OutboxMessages",
            column: "EnqueueTime");

        migrationBuilder.CreateIndex(
            name: "IX_OutboxMessages_ExpirationTime",
            table: "OutboxMessages",
            column: "ExpirationTime");

        migrationBuilder.CreateIndex(
            name: "IX_OutboxMessages_InboxMessageId_InboxConsumerId_SequenceNumber",
            table: "OutboxMessages",
            columns: new[] { "InboxMessageId", "InboxConsumerId", "SequenceNumber" },
            unique: true,
            filter: "[InboxMessageId] IS NOT NULL AND [InboxConsumerId] IS NOT NULL");

        migrationBuilder.CreateIndex(
            name: "IX_OutboxMessages_OutboxId_SequenceNumber",
            table: "OutboxMessages",
            columns: new[] { "OutboxId", "SequenceNumber" },
            unique: true,
            filter: "[OutboxId] IS NOT NULL");

        migrationBuilder.CreateIndex(
            name: "IX_OutboxStates_Created",
            table: "OutboxStates",
            column: "Created");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "audit_events");

        migrationBuilder.DropTable(
            name: "contract_search");

        migrationBuilder.DropTable(
            name: "contract_search_aliases");

        migrationBuilder.DropTable(
            name: "contract_timeline_items");

        migrationBuilder.DropTable(
            name: "import_checkpoints");

        migrationBuilder.DropTable(
            name: "OutboxMessages");

        migrationBuilder.DropTable(
            name: "InboxStates");

        migrationBuilder.DropTable(
            name: "OutboxStates");
    }
}
#pragma warning restore CA1861
