using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable CA1062, CA1861 // Generated by EF Core.

namespace Audit.Infrastructure.Persistence.Migrations;

/// <inheritdoc />
public partial class MoveContractsToArchiveDatabase : Migration
{
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "archive_contract_locators");

            migrationBuilder.DropTable(
                name: "archive_partitions");

            migrationBuilder.DropTable(
                name: "cold_restore_requests");

            migrationBuilder.DropTable(
                name: "restored_timeline_items");

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "LastActivityAt",
                table: "contract_search",
                type: "datetimeoffset",
                nullable: true);

            migrationBuilder.Sql(
                """
                UPDATE contracts
                SET LastActivityAt = activity.LastActivityAt
                FROM contract_search contracts
                CROSS APPLY (
                    SELECT MAX(timeline.OccurredAt) AS LastActivityAt
                    FROM contract_timeline_items timeline
                    WHERE timeline.OrganizationId = contracts.OrganizationId
                      AND timeline.ContractId = contracts.ContractId
                ) activity
                WHERE activity.LastActivityAt IS NOT NULL;

                UPDATE contract_search
                SET LastActivityAt = '1900-01-01T00:00:00+00:00'
                WHERE LastActivityAt IS NULL;
                """);

            migrationBuilder.AlterColumn<DateTimeOffset>(
                name: "LastActivityAt",
                table: "contract_search",
                type: "datetimeoffset",
                nullable: false,
                oldClrType: typeof(DateTimeOffset),
                oldType: "datetimeoffset",
                oldNullable: true);

            migrationBuilder.CreateTable(
                name: "contract_archive_transfers",
                columns: table => new
                {
                    OrganizationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ContractId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    State = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: false),
                    LastActivityAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    SnapshotSequence = table.Column<long>(type: "bigint", nullable: false),
                    EventCount = table.Column<int>(type: "int", nullable: false),
                    TimelineCount = table.Column<int>(type: "int", nullable: false),
                    ErrorCode = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    StartedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_contract_archive_transfers", x => new { x.OrganizationId, x.ContractId });
                });

            migrationBuilder.CreateIndex(
                name: "IX_contract_search_OrganizationId_LastActivityAt",
                table: "contract_search",
                columns: new[] { "OrganizationId", "LastActivityAt" });

            migrationBuilder.CreateIndex(
                name: "IX_contract_archive_transfers_State_UpdatedAt",
                table: "contract_archive_transfers",
                columns: new[] { "State", "UpdatedAt" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "contract_archive_transfers");

            migrationBuilder.DropIndex(
                name: "IX_contract_search_OrganizationId_LastActivityAt",
                table: "contract_search");

            migrationBuilder.DropColumn(
                name: "LastActivityAt",
                table: "contract_search");

            migrationBuilder.CreateTable(
                name: "archive_contract_locators",
                columns: table => new
                {
                    OrganizationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ContractId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ArchivePartitionId = table.Column<Guid>(type: "uniqueidentifier", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_archive_contract_locators", x => new { x.OrganizationId, x.ContractId, x.ArchivePartitionId });
                });

            migrationBuilder.CreateTable(
                name: "archive_partitions",
                columns: table => new
                {
                    ArchivePartitionId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    DataObject = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    ErrorCode = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    EventCount = table.Column<int>(type: "int", nullable: false),
                    Generation = table.Column<int>(type: "int", nullable: false),
                    ManifestObject = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    MaximumSourceSequence = table.Column<long>(type: "bigint", nullable: true),
                    MinimumSourceSequence = table.Column<long>(type: "bigint", nullable: true),
                    Month = table.Column<int>(type: "int", nullable: false),
                    OrganizationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Partition = table.Column<string>(type: "nvarchar(300)", maxLength: 300, nullable: false),
                    Sha256 = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: true),
                    State = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: false),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    Year = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_archive_partitions", x => x.ArchivePartitionId);
                });

            migrationBuilder.CreateTable(
                name: "cold_restore_requests",
                columns: table => new
                {
                    RequestId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CompletedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    ContractId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ErrorCode = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    ExpiresAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    OrganizationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    RequestedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    RestoredEventCount = table.Column<int>(type: "int", nullable: false),
                    StartedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    Status = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_cold_restore_requests", x => x.RequestId);
                });

            migrationBuilder.CreateTable(
                name: "restored_timeline_items",
                columns: table => new
                {
                    EventId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Actor = table.Column<string>(type: "nvarchar(320)", maxLength: 320, nullable: false),
                    ChangeKind = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: false),
                    ChangeTypeCode = table.Column<int>(type: "int", nullable: false),
                    ChangesJson = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ContractId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CorrelationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    DataQualityIssuesJson = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EntityKind = table.Column<string>(type: "nvarchar(80)", maxLength: 80, nullable: false),
                    EntityTypeCode = table.Column<int>(type: "int", nullable: false),
                    ExpiresAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    OccurredAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    OrganizationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    RestoreRequestId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    SourceSequence = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_restored_timeline_items", x => x.EventId);
                });

            migrationBuilder.CreateIndex(
                name: "IX_archive_contract_locators_OrganizationId_ContractId",
                table: "archive_contract_locators",
                columns: new[] { "OrganizationId", "ContractId" });

            migrationBuilder.CreateIndex(
                name: "IX_archive_partitions_OrganizationId_Year_Month_Generation",
                table: "archive_partitions",
                columns: new[] { "OrganizationId", "Year", "Month", "Generation" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_cold_restore_requests_OrganizationId_ContractId_RequestedAt",
                table: "cold_restore_requests",
                columns: new[] { "OrganizationId", "ContractId", "RequestedAt" });

            migrationBuilder.CreateIndex(
                name: "IX_cold_restore_requests_Status_RequestedAt",
                table: "cold_restore_requests",
                columns: new[] { "Status", "RequestedAt" });

            migrationBuilder.CreateIndex(
                name: "IX_restored_timeline_items_ExpiresAt",
                table: "restored_timeline_items",
                column: "ExpiresAt");

            migrationBuilder.CreateIndex(
                name: "IX_restored_timeline_items_OrganizationId_ContractId_SourceSequence",
                table: "restored_timeline_items",
                columns: new[] { "OrganizationId", "ContractId", "SourceSequence" });
        }
}
