using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable CA1062, CA1861 // Generated by EF Core.

namespace Audit.Infrastructure.Persistence.Migrations;

/// <inheritdoc />
public partial class SupportLateArchiveBatches : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropIndex(
            name: "IX_archive_partitions_OrganizationId_Year_Month",
            table: "archive_partitions");

        migrationBuilder.AddColumn<int>(
            name: "Generation",
            table: "archive_partitions",
            type: "int",
            nullable: false,
            defaultValue: 0);

        migrationBuilder.CreateIndex(
            name: "IX_archive_partitions_OrganizationId_Year_Month_Generation",
            table: "archive_partitions",
            columns: new[] { "OrganizationId", "Year", "Month", "Generation" },
            unique: true);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropIndex(
            name: "IX_archive_partitions_OrganizationId_Year_Month_Generation",
            table: "archive_partitions");

        migrationBuilder.DropColumn(
            name: "Generation",
            table: "archive_partitions");

        migrationBuilder.CreateIndex(
            name: "IX_archive_partitions_OrganizationId_Year_Month",
            table: "archive_partitions",
            columns: new[] { "OrganizationId", "Year", "Month" },
            unique: true);
    }
}
#pragma warning restore CA1861
