using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable CA1062, CA1861 // Generated by EF Core.

namespace Audit.Infrastructure.Persistence.Migrations;

/// <inheritdoc />
public partial class AddArchiveLifecycle : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "archive_contract_locators",
            columns: table => new
            {
                OrganizationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                ContractId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                ArchivePartitionId = table.Column<Guid>(type: "uniqueidentifier", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_archive_contract_locators", x => new { x.OrganizationId, x.ContractId, x.ArchivePartitionId });
            });

        migrationBuilder.CreateTable(
            name: "archive_partitions",
            columns: table => new
            {
                ArchivePartitionId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                OrganizationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                Year = table.Column<int>(type: "int", nullable: false),
                Month = table.Column<int>(type: "int", nullable: false),
                Partition = table.Column<string>(type: "nvarchar(300)", maxLength: 300, nullable: false),
                State = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: false),
                EventCount = table.Column<int>(type: "int", nullable: false),
                MinimumSourceSequence = table.Column<long>(type: "bigint", nullable: true),
                MaximumSourceSequence = table.Column<long>(type: "bigint", nullable: true),
                DataObject = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                ManifestObject = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                Sha256 = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: true),
                ErrorCode = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                UpdatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_archive_partitions", x => x.ArchivePartitionId);
            });

        migrationBuilder.CreateTable(
            name: "cold_restore_requests",
            columns: table => new
            {
                RequestId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                OrganizationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                ContractId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                Status = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false),
                RequestedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                StartedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                CompletedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                ExpiresAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                RestoredEventCount = table.Column<int>(type: "int", nullable: false),
                ErrorCode = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_cold_restore_requests", x => x.RequestId);
            });

        migrationBuilder.CreateTable(
            name: "restored_timeline_items",
            columns: table => new
            {
                EventId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                OrganizationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                ContractId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                RestoreRequestId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                SourceSequence = table.Column<long>(type: "bigint", nullable: false),
                OccurredAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                CorrelationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                ChangeTypeCode = table.Column<int>(type: "int", nullable: false),
                ChangeKind = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: false),
                EntityTypeCode = table.Column<int>(type: "int", nullable: false),
                EntityKind = table.Column<string>(type: "nvarchar(80)", maxLength: 80, nullable: false),
                Actor = table.Column<string>(type: "nvarchar(320)", maxLength: 320, nullable: false),
                ChangesJson = table.Column<string>(type: "nvarchar(max)", nullable: false),
                DataQualityIssuesJson = table.Column<string>(type: "nvarchar(max)", nullable: false),
                ExpiresAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_restored_timeline_items", x => x.EventId);
            });

        migrationBuilder.CreateIndex(
            name: "IX_archive_contract_locators_OrganizationId_ContractId",
            table: "archive_contract_locators",
            columns: new[] { "OrganizationId", "ContractId" });

        migrationBuilder.CreateIndex(
            name: "IX_archive_partitions_OrganizationId_Year_Month",
            table: "archive_partitions",
            columns: new[] { "OrganizationId", "Year", "Month" },
            unique: true);

        migrationBuilder.CreateIndex(
            name: "IX_cold_restore_requests_OrganizationId_ContractId_RequestedAt",
            table: "cold_restore_requests",
            columns: new[] { "OrganizationId", "ContractId", "RequestedAt" });

        migrationBuilder.CreateIndex(
            name: "IX_cold_restore_requests_Status_RequestedAt",
            table: "cold_restore_requests",
            columns: new[] { "Status", "RequestedAt" });

        migrationBuilder.CreateIndex(
            name: "IX_restored_timeline_items_ExpiresAt",
            table: "restored_timeline_items",
            column: "ExpiresAt");

        migrationBuilder.CreateIndex(
            name: "IX_restored_timeline_items_OrganizationId_ContractId_SourceSequence",
            table: "restored_timeline_items",
            columns: new[] { "OrganizationId", "ContractId", "SourceSequence" });
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "archive_contract_locators");

        migrationBuilder.DropTable(
            name: "archive_partitions");

        migrationBuilder.DropTable(
            name: "cold_restore_requests");

        migrationBuilder.DropTable(
            name: "restored_timeline_items");
    }
}
#pragma warning restore CA1861
